version: "3"
services:
  web:
    image: emaxwell14/react-scaffolding:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
      restart_policy:
         condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
